spring:
  application:
    name: server
  profiles:
    active: ${user_env:dev} #多环节配置
  jackson:
    serialization:
      write-dates-as-timestamps: true
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080
  servlet:
    context-path: "/${spring.application.name}"

logging:
  level:
    vip.ylove: info

cors:
  allowOrigin:
    url: ${cors_allow_origin_url:*}
    enable: ${cors_allow_origin_enable:true}

st:
  encrypt:
    privateKey: 'MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIcDbaSFraZGQiaHVeoErVYfl3+SKBUDZYAEog+u9AxISFWs8/e3b5WuRH1jHDB0IfyWC8KVtUHU5whu2sK6uCs9RriHkpaa0MXmFhtRDWqG8EjIJWKBcwx29LhRHvxq5UeDQYj0OrXBnpvWHNlB0T0pz4Fj+jvb4h7CuTzhwDdpAgMBAAECgYBFsQJWq14wdxHMW42Ah7uFujb0ddhUyHULONkCqXd2I5WbC/S/CKQDqnnWE2PIqxmkDTuyzJ5Mhf5fvwETBVjs0JpxOe8m6NPhtV2j4eoiUGTIEggAN0zn0Ayk9b1VqYJ0SZs3WoVanTRFjuLSHtuInXrKdayVLkyxuUGwewmSAQJBAMYPOKS0yMRZP87rGric2i+8otXcXwr4+snrTexOvvLwGOqIezRX0AZy9c1JihM5pRcTCIh1OFEEHGZBmXmtsSkCQQCugqdFpEreIHLKpJ/2VEZfRoh66GXSkIF4dFvqERr+C34R2BDFXgyle6Vnuemuk2u4WtZIMCsfCB1NQOt/D9xBAkBpSLIdrBSFe8QVpJjBxm+drLMK6GiFlrEKIVF86qdK0SMNmZuUyZFFvFq50/vYGG6QA4gnsdhMCNln6jtBmXlxAkA+W11eGzjNapbaJj0qji6fONrn4EcSGKTK3/lACGC2ynB/+87yV4r5Ttdp2xrPUMo7E+ph3SRrcEDYLAx6WLaBAkByjHmr8/2PJhMnbDcWepTRPL+nT/HpbZzxFiHnivRsC9McOLARWou3hEEirIkkrKWZW7G1gAXF9VwU6DX9PAjA'
    enable-global-encrypt: false
    close-global-encrypt: false




