spring:
  application:
    name: client
  profiles:
    active: ${user_env:dev} #多环节配置
  jackson:
    #    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8081
  servlet:
    context-path: "/${spring.application.name}"

logging:
  level:
    vip.ylove: debug

st:
  encrypt:
    publicKey: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCHA22kha2mRkImh1XqBK1WH5d/kigVA2WABKIPrvQMSEhVrPP3t2+VrkR9YxwwdCH8lgvClbVB1OcIbtrCurgrPUa4h5KWmtDF5hYbUQ1qhvBIyCVigXMMdvS4UR78auVHg0GI9Dq1wZ6b1hzZQdE9Kc+BY/o72+Iewrk84cA3aQIDAQAB'
    appId: '123456'
    appAuth: '123456'